### ISSUE TITLE
Add Bower Support

### ISSUE THREAD

**Issue by robneu** [thatryan/gravity-forms-sass#1]
This is awesome! Is there any way you could add Bower support for the repo? It's pretty simple to set up and I'll love you forever. :)

http://bower.io/docs/creating-packages/

**Comment by jackmcconnell** [comment]
I second this. Would mean we could install it from within CodeKit.

**Comment by thatryan** [comment]
Great idea, will definitely do this.

**Comment by GaryJones** [comment]
+1 for bower support.

**Comment by thatryan** [comment]
Sorry took a bit to get around to this,but boom. Added.
Let me know if run into any issues, 

`bower install gravity-forms-sass` should get ya there ;)
