### ISSUE TITLE
Example Form Export File

### ISSUE THREAD

**Issue by halian-vilela** [thatryan/gravity-forms-sass#3]
Hi, could you provide the XML to import your form example (visual overview), I would like to use it to make some tests with the .scss  also.

**Comment by thatryan** [comment]
I have included that file in the repo, `gravity-forms-sass-testing-forms.xml` can be imported into GF for the demo forms. Is that what you are referring to?

**Comment by GaryJones** [comment]
Example form works very well!

**Comment by halian-vilela** [comment]
Very nice thanks!
