### ISSUE TITLE
Create develop branch

### ISSUE THREAD

**Issue by GaryJones** [thatryan/gravity-forms-sass#7]
I'm currently pulling in the .scss files from this repo via Bower, so it would be great if development could follow the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) approach, where the `develop` branch was selected as the main branch (See repo Settings), and was the active recipient for PRs, and `master` was kept as a clean branch against which Bower could pull against, until such time as the repo was mature enough to do versioned releases and tags.

**Comment by thatryan** [comment]
Love this idea and think I have seen other doing it so I know what you mean, will look into it (hopefully) tonight :+1:

**Comment by thatryan** [comment]
done and done.
